controller_list:
  - name: fake_so_arm100_controller
    type: $(arg fake_execution_type)
    joints:
      - Shoulder_Rotation
      - Shoulder_Pitch
      - Elbow
      - Wrist_Pitch
      - Wrist_Roll
      - Gripper
initial:  # Define initial robot poses per group
#  - group: so_arm100
#    pose: home

  []