controller_list:
  - name: fake_so100_controller
    type: $(arg fake_execution_type)
    joints:
      - Shoulder_Rotation
      - Shoulder_Pitch
      - Elbow
      - Wrist_Pitch
      - Wrist_Roll
initial:  # Define initial robot poses per group
  - group: so100
    pose: init_pose