so_arm100_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Shoulder_Rotation
    - Shoulder_Pitch
    - Elbow
    - Wrist_Pitch
    - Wrist_Roll
    - Gripper
  gains:
    Shoulder_Rotation:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Shoulder_Pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Wrist_Pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Wrist_Roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Gripper:
      p: 100
      d: 1
      i: 1
      i_clamp: 1